parameters:
#    ctj_register.example.class: Ctj\RegisterBundle\Example

services:
#    ctj_register.example:
#        class: %ctj_register.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
